import { ISocketEvents } from '@shared/models/socketEvents.model';

export const SOCKET_EVENTS: ISocketEvents = {
  CL_SEND_JOIN_ROOM: 'CL_SEND_JOIN_ROOM',
  SV_SEND_JOIN_ROOM: 'SV_SEND_JOIN_ROOM',

  CL_SEND_PLAYER_POSITION: 'CL_SEND_PLAYER_POSITION',
  SV_SEND_PLAYER_POSITION: 'SV_SEND_PLAYER_POSITION',

  CL_SEND_ADD_OBJECT: 'CL_SEND_ADD_OBJECT',
  SV_SEND_ADD_OBJECT: 'SV_SEND_ADD_OBJECT',

  SV_SEND_DISCONNECTION: 'SV_SEND_DISCONNECTION'
};
