import { ISocketEvents } from '@online/models/socketEvents.model';

export const SOCKET_EVENTS: ISocketEvents = {
  CL_SEND_JOIN_ROOM: 'CL_SEND_JOIN_ROOM',
  SV_SEND_JOIN_ROOM: 'SV_SEND_JOIN_ROOM',

  CL_SEND_PLAYER_POSITION: 'CL_SEND_PLAYER_POSITION',
  SV_SEND_PLAYER_POSITION: 'SV_SEND_PLAYER_POSITION',

  CL_SEND_ADD_OBJECT: 'CL_SEND_ADD_OBJECT',
  SV_SEND_ADD_OBJECT: 'SV_SEND_ADD_OBJECT',

  CL_SEND_REMOVE_OBJECT: 'CL_SEND_REMOVE_OBJECT',
  SV_SEND_REMOVE_OBJECT: 'SV_SEND_REMOVE_OBJECT',

  CL_SEND_MESSAGE: 'CL_SEND_MESSAGE',
  SV_SEND_MESSAGES: 'SV_SEND_MESSAGES',

  SV_SEND_DISCONNECTION: 'SV_SEND_DISCONNECTION'
};
