declare module '*.css' { export default '' as string; }
declare module '*.scss' { export default '' as string; }
declare module '*.html' { export default '' as string; }
declare module '*.obj' { export default '' as string; }
declare module '*.mtl' { export default '' as string; }
declare module '*.glsl' { export default '' as string; }
declare module '*.png' { export default '' as string; }
declare module '*.svg' { export default '' as string; }
declare module '*.mp3' { export default '' as string; }
